### ISSUE TITLE
UTF-8 fix for Auto Hot Key implementation in Nexss Programmer

### ISSUE THREAD

**Issue by nexssp** [nexssp/language_ahk#1]
When I do test for unicode characters I receive wrong result for example:

![image](https://user-images.githubusercontent.com/53263666/72952350-dfa66e00-3d91-11ea-83bd-6ef98082da22.png)

For C++ for example is ok.

**Comment by mapoart** [comment]
```ahk
ConvertUtf8(string)
{
    var := "x"
    ; Ensure capacity.
    len := StrPut(string, "UTF-8")    
    VarSetCapacity( var, len)
    ; convert the string.
    StrPut(string, &var, len, "CP0")
    return StrGet(&var, len, "CP0")        
}

myvar := "Det stÃ¥r klart att nÃ¥gon har tjallat om gÃ¶mstÃ¤llet."
; the converted string should read "Det står klart att någon har tjallat om gömstället."
myANSI := ConvertUtf8(myvar)
msgbox % myANSI
```
Found here:
https://autohotkey.com/board/topic/44027-how-to-work-with-utf-8/

**Comment by mapoart** [comment]
Done ! additionaly without extra libraries:

![image](https://user-images.githubusercontent.com/8799218/72954212-f6e85a00-3d97-11ea-99a0-4bdaca254c78.png)

JSON utf-8 in Auto Hot Key:
```ahk
(oHTML:=ComObjCreate("HTMLFile")).write("<!DOCTYPE html><html><head><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta charset=""utf-8"" /></head><body></body></html>")

MyObject:= oHTML.parentWindow.JSON.parse(JsonString)

JsonString:= oHTML.parentWindow.JSON.stringify(MyObject)
```

This has been found here: <https://www.autohotkey.com/boards/viewtopic.php?t=53402>

**Comment by nexssp** [comment]
![image](https://user-images.githubusercontent.com/53263666/72957481-08376380-3da4-11ea-9ce9-50750237fd86.png)
